- id: 10.1093/gigascience/giz041
  image: https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Scientific_journal_icon.svg/1024px-Scientific_journal_icon.svg.png

- id: 10.1093/bioinformatics/btx554
  image: https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Scientific_journal_icon.svg/1024px-Scientific_journal_icon.svg.png

- id: 10.3390/jof6040364
  image: https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Scientific_journal_icon.svg/1024px-Scientific_journal_icon.svg.png

- id: 10.1099/mic.0.001088
  image: https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Scientific_journal_icon.svg/1024px-Scientific_journal_icon.svg.png

- id: 10.1093/mmy/myaa062
  image: https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Scientific_journal_icon.svg/1024px-Scientific_journal_icon.svg.png

- id: 10.1371/journal.pntd.0007576
  image: https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Scientific_journal_icon.svg/1024px-Scientific_journal_icon.svg.png
  
- id: 10.3390/ijms22115628
  image: https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Scientific_journal_icon.svg/1024px-Scientific_journal_icon.svg.png

- id: 10.3389/fevo.2021.650783
  image: https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Scientific_journal_icon.svg/1024px-Scientific_journal_icon.svg.png

- id: 10.12688/f1000research.26524.1
  image: https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Scientific_journal_icon.svg/1024px-Scientific_journal_icon.svg.png

- id: 10.3389/fevo.2020.579965
  image: https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Scientific_journal_icon.svg/1024px-Scientific_journal_icon.svg.png

- id: 10.1021/acs.biochem.6b00886
  image: https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Scientific_journal_icon.svg/1024px-Scientific_journal_icon.svg.png

- id: 10.1007/s00438-016-1184-1
  image: https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Scientific_journal_icon.svg/1024px-Scientific_journal_icon.svg.png

- id: 10.1128/genomeA.01124-16
  image: https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Scientific_journal_icon.svg/1024px-Scientific_journal_icon.svg.png

- id: 10.30574/msarr.2022.4.2.0026
  image: https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Scientific_journal_icon.svg/1024px-Scientific_journal_icon.svg.png

- id: 10.30574/gscarr.2022.10.2.0037
  image: https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Scientific_journal_icon.svg/1024px-Scientific_journal_icon.svg.png

- id: 10.1007/s10126-021-10081-0
  image: https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Scientific_journal_icon.svg/1024px-Scientific_journal_icon.svg.png

- id: 10.1016/j.aquaculture.2022.738581
  image: https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Scientific_journal_icon.svg/1024px-Scientific_journal_icon.svg.png
